services:

  db:
    image: postgres:16-alpine
    container_name: work_planner-db
    env_file:
      - path: .env
        required: false
    volumes:
      - work_planner_postgres_data:/var/lib/postgresql/data:Z
    ports:
      - "5432:5432"

  app:
    image: work_planner:latest
    build:
      context: .
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    command: work_planner
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  work_planner_postgres_data: {}
